name: Performance tests
on:
  # TODO(senichenkov): use right conditions here
  push:
    branches:
      # FORK ONLY
        - performance-testing
        - performance-testing-timeweb
        - performance-testing-regru
  # Note: schedule only triggers on `main` branch
  # Schedule may be deactivated in some cases. For information on how to re-activate it, see
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  schedule:
    # GitHub recommends not to start jobs at the start of the hour
    # 6 is Saturday (currently day of the general meeting)
    - cron: 30 12 * * 6
  workflow_dispatch:
    # Here go parameters -- may be useful

jobs:
  turn-test-server-on:
    runs-on: ubuntu-latest
    steps:
      - name: Turn test server on
        run: |
          ANSW=$(curl -X POST \
          -H "Authorization: Bearer ${{ secrets.REGRU_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"type": "start"}' \
          'https://api.cloudvps.reg.ru/v1/reglets/${{ vars.REGRU_SERVER_ID }}/actions')

          # I don't know if this API returns something
          # if [[ $ANSW -ne 204 ]]; then
          #   echo "HTTP error $ANSW"
          #   exit 1
          # fi
      - name: Wait for the server to start
        run: sleep 30

  performance-tests:
    runs-on: [self-hosted, RegRu]
    needs: turn-test-server-on
    env:
      LogDirName: /home/github-user/performance-tests
      OldFilename: # set dynamically
      NewFilename: # set dynamically
    steps:
      # GitHub creates new clear VM on its runner here
      # Without this step checkout is unable to clear repository, because `lib` somehow
      # contains files, owned by `root`
      - name: Clear working directory
        run: sudo rm -rf ${{ github.workspace }}/*
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies
        with:
          os: ubuntu-latest
          toolset: gcc
      - name: Download datasets
        uses: ./.github/composite-actions/download-datasets
      - name: Build
        run: |
          export CXX=g++-10
          ./build.sh
      - name: Test
        working-directory: ${{github.workspace}}/build/target
        run: |
          ./Desbordante_test --gtest_filter='*PerformanceTests*' \
           --gtest_output=json:${{ github.workspace }}/gtest_output.json
      - name: Select latest log
        run: |
          echo "OldFilename=$(ls ${{ env.LogDirName }} | grep -o "results-[0-9|:|-]*\.json" | \
          tail -n 1)" >> $GITHUB_ENV
      - name: Copy latest log
        run: |
          if [[ -z "${{ env.OldFilename }}" ]]; then
            echo "No file selected. Using empty JSON"
            # There are 2 possible problems:
            #   1. No such directory
            #   2. Directory is empty or doesn't contain any file that match regexp
            mkdir -p ${{ env.LogDirName }}
            echo "{}" > ${{ github.workspace }}/prev-results.json
          else
            cp ${{ env.LogDirName }}/${{ env.OldFilename }} \
             ${{ github.workspace }}/prev-results.json
          fi
      - name: Read downloaded file
        run: cat ${{ github.workspace }}/prev-results.json
      - name: Parse test results
        working-directory: ${{ github.workspace }}
        run: |
          python3 src/tests/performance_tests/performance_tests.py \
           gtest_output.json curr-results.json prev-results.json
      - name: Read current results
        run: cat ${{ github.workspace }}/curr-results.json
      - name: Select filename
        shell: bash
        run: echo "NewFilename=results-$(date +%F-%H:%M:%S).json" >> $GITHUB_ENV
      - name: Save current results
        run: |
          cp ${{ github.workspace }}/curr-results.json ${{ env.LogDirName }}/${{ env.NewFilename }}

  # If there's more than N files saved, purge the oldest ones
  purge-old-results:
    needs: performance-tests
    runs-on: [self-hosted, RegRu]
    env:
      # Name of folder with test results
      LogDirName: /home/github-user/performance-tests
      # Number of files to keep
      N: 100
    steps:
      - name: Purge old files
        shell: bash
        run: |
          function get_num() {
            echo $(ls ${{ env.LogDirName }} | wc -l)
          }
          function get_first() {
            echo $(ls ${{ env.LogDirName }} | grep -o "results-[0-9|:|-]*\.json" | head -n1)
          }

          while [ $(get_num) -gt ${{ env.N }} ]; do
            rm ${{ env.LogDirName }}/$(get_first)
          done

  build-plot:
    runs-on: [self-hosted, Regru]
    needs: performance-tests
    env:
      # File to store test results
      Filename: # no value
      # Name of folder with test results
      LogDirName: /home/github-user/performance-tests
    steps:
      - name: Install matplotlib
        run: sudo apt install -y python3-matplotlib
      - name: Build plots
        working-directory: ${{ github.workspace }}
        run: |
          python3 src/tests/performance_tests/display_performance_tests.py \
           ${{ env.LogDirName }} plots.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: plots.pdf
          path: ${{ github.workspace }}/plots.pdf
          if-no-files-found: error

  turn-test-server-off:
    runs-on: ubuntu-latest
    needs: [build-plot, purge-old-results]
    # Even if previous jobs failed
    # TODO(senichenkov): this shouldn't run if same job is running concurrently
    if: always()
    steps:
      - name: Wait a little
        run: sleep 5
      - name: Turn test server off
        run: |
          ANSW=$(curl -X POST \
          -H "Authorization: Bearer ${{ secrets.REGRU_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"type": "stop"}' \
          'https://api.cloudvps.reg.ru/v1/reglets/${{ vars.REGRU_SERVER_ID }}/actions')

          # I don't know if this API returns something
          # if [[ $ANSW -ne 204 ]]; then
          #   echo "HTTP error $ANSW"
          #   exit 1
          # fi
